### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by natsinger** [OanaIgnat/reddit_inspiring_posts#1]
the extract_reddit_data method calling the fetchObjects method doesn't seems to work, it is returning an 'NoneType' error 

 
~\AppData\Local\Temp\ipykernel_13932\1186839699.py in extract_reddit_data(**kwargs)
     20 
     21         # Loop the returned data, ordered by date
---> 22         for object in objects:
     23             id = int(object['id'],36)
     24             if id > max_id:

TypeError: 'NoneType' object is not iterable

could be great if someone had a quick fix

**Comment by OanaIgnat** [comment]
I'm sorry, here is the inspirational data.
[data_inspir.csv](https://github.com/MichiganNLP/Reddit-Detect-Inspiration/files/13981367/data_inspir.csv)
